### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by priv-kweihmann** [vinland-technology/flict#80]
Still no pypi release is available nor this is mentioned in the README.
I think it would be best to release tagged versions to pypi (as sdist) to let people use this tool, without the need to use git

**Comment by hesa** [comment]
What is needed to get there?

**Comment by hesa** [comment]
Created an account and followed some procedures... might have made: https://pypi.org/project/flict/

**Comment by priv-kweihmann** [comment]
whoop whoop - it's done!

**Comment by hesa** [comment]
```
$ pip3 install flict
Collecting flict
  Using cached flict-0.1.tar.gz (78 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/hesa/tmp/flict-try/tmp/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_waxdwv9/flict_5f419f7da9f94d5db95bd9471444e317/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_waxdwv9/flict_5f419f7da9f94d5db95bd9471444e317/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qx4ja2s9
         cwd: /tmp/pip-install-_waxdwv9/flict_5f419f7da9f94d5db95bd9471444e317/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_waxdwv9/flict_5f419f7da9f94d5db95bd9471444e317/setup.py", line 12, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/08/4f/416fe0b1df1038eeb6e02678b682ce835dfec371eb6c41cc4dde115276c0/flict-0.1.tar.gz#sha256=93f27c49973a2e6eb6bbfbdffc29dbfa19f2f393281fbcf1010223bf341c7757 (from https://pypi.org/simple/flict/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement flict (from versions: 0.1)
ERROR: No matching distribution found for flict
```

**Comment by priv-kweihmann** [comment]
This is done now
